backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"
pluralizelisttitles: false
paginate: 4
paginatePath: "page"
collections: # A list of collections the CMS should be able to edit
  - name: "products"
    label: "Товары"
    folder: "site/content/products"
    create: true
    fields:
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Краткое описание", name: "description", widget: "text"}
      - {label: "Изображение", name: "image", widget: "image", required: false}
      - {label: "Стоимость", name: "price", widget: "number", valueType: "float", min: 0}
